# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# title: "\"
#title_prefix: "jared@trigili.com:"
# description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://trigili.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
permalink: /:year/:month/:day/:title.html

header_pages:
    - index.md
    - about.md
    - blog.md

# Build settings
# remote_theme: b2a3e8/jekyll-theme-console
theme: jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
footer: <script>document.write('<'+'a'+' '+'h'+'r'+'e'+'f'+'='+"'"+'m'+'&'+'#'+'9'+'7'+';'+'i'+'l'+'t'+'o'+'&'+'#'+'5'+'8'+';'+'&'+'#'+'1'+'0'+'6'+';'+'&'+'#'+'9'+'7'+';'+'r'+'e'+'d'+'%'+'4'+'0'+'t'+'r'+'i'+'&'+'#'+'1'+'0'+'3'+';'+'i'+'%'+'&'+'#'+'5'+'4'+';'+'C'+'i'+'&'+'#'+'4'+'6'+';'+'%'+'6'+'&'+'#'+'5'+'1'+';'+'&'+'#'+'3'+'7'+';'+'6'+'&'+'#'+'7'+'0'+';'+'m'+"'"+'>'+'j'+'a'+'&'+'#'+'1'+'1'+'4'+';'+'&'+'#'+'1'+'0'+'1'+';'+'d'+'&'+'#'+'6'+'4'+';'+'t'+'r'+'i'+'&'+'#'+'1'+'0'+'3'+';'+'i'+'l'+'i'+'&'+'#'+'4'+'6'+';'+'c'+'o'+'m'+'<'+'/'+'a'+'>');</script><noscript>[Turn on JavaScript to see the email address]</noscript>

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#   - exclude jekyll.sh